#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.otus.otuskotlin.homelibrary.app.ktor.ApplicationKt.module"
#  urls:
#    - "http://127.0.0.1:8080/v1"
#    - "http://0.0.0.0:8080/v1"
#    - "http://192.168.0.182:8080/v1"
  logger: kmp
#  # Логирование типа socket требует установки в fluent-bit.conf
#  # [INPUT]
#  # Name    TCP # Вот здесь нужно поменять!
#  # Listen  0.0.0.0
#  # Port    24224
#  logger: socket
#  socketLogger:
#    port: 24224

homelibrary:
  repository:
    test: "inmemory"
    prod: "$DB_TYPE_PROD:inmemory"
    psql:
      schema: public
      database: "$HMLREDS_DB:homelibrary-eds"
      host: "HMLREDS_HOST:localhost"
      port: "$HMLREDS_PORT:5432"
      user: "$HMLREDS_USER:postgres"
      password: "$HMLREDS_PASS:homelibrary-pass"
